version: '3'

services:
  my1dbos:
      image: mysql:5.7
      volumes:
            -mysql_db:/var/lib/mysql
      restart: always
      environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_USER: jeet
            MYSQL_PASSWORD: redhat11
            MYSQL_DATABASE: my1db

wp1os:
      image: wordpress:5.1.1-php7.3-apache    
      restart: always
      depends_on:
           - db1os
      ports:
           - 8080:80               
                 volumes: 
                           - wordpress:/var/www/html
                 restart: always
                 environment:
                          WORDPRESS_DB_HOST: db1os
                          WORDPRESS_DB_USER: my1dbos
                          WORDPRESS_DB_PASSWORD: redhat11
                          WORDPRESS_DB_NAME: my1db
volumes:
        mysql_db:
        wordpress: 